### PR TITLE
Support Laravel ^7

### PR DESCRIPTION
**Pull request by caiokawasaki**
@jamesmills could you check this out?

### CODE REVIEW

**Comment by Kamalito75** [comment]
Hi @jamesmills . Could you please push this?

**Comment by jamesmills** [comment]
Done here. Thanks.

https://github.com/jamesmills/eloquent-uuid/pull/17

**Comment by caiokawasaki** [comment]
Sad =( I have pulled first haha

**Comment by jamesmills** [comment]
Sorry about that @caiokawasaki. Thank you.

**Pull request closed without merging**
